import Head from 'next/head'
import MainPageShell from '../components/app_shell'
import SearchPage from '../components/search_page'

export default function Home() {
  return (
    <>
      <Head>
        <title>Langtool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPageShell>
          <SearchPage> <></> </SearchPage>
        </MainPageShell>
      </main>
    </>
  )
}
